image: node:12.8.1

pipelines:
  branches:
    master:
      - step:
          name: build the angular
          script:
            - npm install
            - npm install -g @angular/cli
            - ng build --prod
          artifacts:
            - dist/**
      - step:
          name: Login and build the docker image
          script: # Modify the commands below to build your repository.
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build -t givt/givtdashboard2 .
            - docker push givt/givtdashboard2
          services:
            - docker