image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Login and build the docker image
          script: # Modify the commands below to build your repository.
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build --build-arg CONFIGURATION=prod -t givt/givtdashboard2:master .
            - docker push givt/givtdashboard2:master
          services:
            - docker
    develop:
      - step:
          name: Login and build the docker image
          script: # Modify the commands below to build your repository.
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build -t givt/givtdashboard2:pre .
            - docker push givt/givtdashboard2:pre
          services:
            - docker