pipelines:
  branches:
    master:
      - step:
          name: Login with docker
          script:
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - step:
          name: Build the docker image
          script: # Modify the commands below to build your repository.
            - docker build -t givt/givtdashboard2 .
      - step:
          name: Push the docker image
          script:
            - docker push givt/givtdashboard2