image: node:6.9.4

pipelines:
  branches:
    master:
       - step:
          name: build the angular
          script:
            - ng build --prod
      - step:
          name: Login with docker
          script:
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          services:
            - docker
      - step:
          name: Build the docker image
          script: # Modify the commands below to build your repository.
            - docker build -t givt/givtdashboard2 .
          services:
            - docker
      - step:
          name: Push the docker image
          script:
            - docker push givt/givtdashboard2
          services:
            - docker